name: Release

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download Windows build artifact
        uses: actions/download-artifact@v4
        with:
          name: release-tls-windows-latest
          path: release/windows

      - name: Download macOS build artifact
        uses: actions/download-artifact@v4
        with:
          name: release-tls-macos-latest
          path: release/macos

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install

      - name: Extract changelog
        id: changelog
        run: |
          echo "notes<<EOF" >> $GITHUB_OUTPUT
          node scripts/extract-changelog.js >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.run_number }}
          body: ${{ steps.changelog.outputs.notes }}
          files: |
            release/windows/*.exe
            release/windows/*.blockmap
            release/windows/latest*.yml
            release/macos/*.dmg
            release/macos/*.blockmap
            release/macos/latest*.yml
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
