name: Release

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Windows build artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          name: release-artifact-windows-latest
          path: release/windows
          run_id: ${{ github.event.workflow_run.id }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download macOS build artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          name: release-artifact-macos-latest
          path: release/macos
          run_id: ${{ github.event.workflow_run.id }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install

      - name: Extract changelog
        id: changelog
        run: |
          echo "notes<<EOF" >> $GITHUB_OUTPUT
          node scripts/extract-changelog.js >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Get package version
        id: package-version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Debug - List downloaded files
        run: |
          echo "=== Listing all files in release directory ==="
          find release -type f -ls || echo "No release directory found"
          echo "=== Directory structure ==="
          tree release || find release -type d
          echo "=== Checking for specific file types ==="
          find release -name "*.exe" -ls || echo "No exe files found"
          find release -name "*.dmg" -ls || echo "No dmg files found"
          find release -name "*.blockmap" -ls || echo "No blockmap files found"
          find release -name "latest*.yml" -ls || echo "No yml files found"

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.package-version.outputs.version }}
          name: Release v${{ steps.package-version.outputs.version }}
          body: ${{ steps.changelog.outputs.notes }}
          files: |
            release/**/*.exe
            release/**/*.dmg
            release/**/*.blockmap
            release/**/latest*.yml
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
